---
name: Publish Stage branch to Main

on:
  # Runs on merged pull_request: to stage branch
  pull_request:
    branches:
      - stage
    types:
      - closed

  # Enable manual start button
  workflow_dispatch:

jobs:
  sync:
    name: 'Publish Stage branch to Main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo_playbooks
          ref: stage
          
      - name: Transformation tasks
        working-directory: repo_playbooks
        run: |
          cp playbook.yml playbook_copy.yml

          sed 's/^---/\n/g' fragment.yml >> vars.yml

          echo "Append line" >> playbook.yml

          git rm fragment.yml

      - name: Check for changes
        working-directory: repo_playbooks
        id: check_changes
        run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit changes
        working-directory: repo_playbooks
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin
          get branch -f main
          git push origin main --force
