---
name: Publish Stage branch to Main

on:
  # Runs on merged pull_request: to stage branch
  pull_request:
    branches:
      - stage
    types:
      - closed

  # Enable manual start button
  workflow_dispatch:

jobs:
  sync:
    name: 'Publish Stage branch to Main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: repo_playbooks
          ref: stage
          
      - name: Transformation tasks
        working-directory: repo_playbooks
        run: |
          shopt -s nullglob  # Ensures that empty results are empty

          # Loop through all deploy_scenarios
          for dir in ./deploy_scenarios/*; do
            file=("$dir"/ansible_extravars.yml)

            if [[ -f "$file" ]]; then
              # Copy ansible_requirements
              cp ./common_fragments/ansible_requirements.yml $dir/

              fragment_vars="common_fragments/fragment.yml"
              if [ -f "$fragment_vars" ]; then
                sed 's/^---/\n/g' "$fragment_vars" >> "$file"
              fi  # if fragment_vars exists

            fi  # if base files were found
          done

          cp playbook.yml playbook_copy.yml

          echo "Append line" >> playbook.yml

          git rm -rf ./common_fragments

          ls -la

          shopt -u nullglob

      - name: Force push changes
        working-directory: repo_playbooks
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin
          git branch -f main
          git push origin main --force
